// KOF97 sprite 类型定义
// Generated by assets-raw/kof97/build-firmware-sprites.js
// 不要手改; 改 sprite 请重跑脚本
#pragma once

#include <Arduino.h>
#include <pgmspace.h>

struct KofSprite {
  uint8_t  w;
  uint8_t  h;
  uint16_t pixelCount;
  const uint8_t* pixels;
  uint8_t  fmt;     // 5 = [x, y, r, g, b] 每像素 5 字节
};

// 一个角色的 stance 动画: 多帧 sprite 数组
struct KofStanceSet {
  uint8_t frameCount;
  const KofSprite* const* frames;
};
