$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Drawing

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceDir = Join-Path $scriptDir "cuts/timefont"
$outputPath = Join-Path $scriptDir "timefont-pixels.js"
$digitOrder = @("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")

$darkBlue = "#21428c"
$lightBlue = "#5a8cbd"
$yellow = "#d6de31"

function Test-IsYellowCorePixel($color) {
  if ($color.A -eq 0) {
    return $false
  }

  $dr = [Math]::Abs([int]$color.R - 214)
  $dg = [Math]::Abs([int]$color.G - 222)
  $db = [Math]::Abs([int]$color.B - 49)

  return ($dr -le 10 -and $dg -le 10 -and $db -le 10)
}

function Get-ExpandedMask([bool[,]]$sourceMask, [int]$width, [int]$height) {
  $expanded = New-Object 'bool[,]' $width, $height

  for ($y = 0; $y -lt $height; $y++) {
    for ($x = 0; $x -lt $width; $x++) {
      $hit = $false
      for ($dy = -1; $dy -le 1 -and -not $hit; $dy++) {
        for ($dx = -1; $dx -le 1; $dx++) {
          $nx = $x + $dx
          $ny = $y + $dy
          if ($nx -lt 0 -or $ny -lt 0 -or $nx -ge $width -or $ny -ge $height) {
            continue
          }
          if ($sourceMask[$nx, $ny]) {
            $hit = $true
            break
          }
        }
      }

      if ($hit) {
        $expanded[$x, $y] = $true
      }
    }
  }

  return ,$expanded
}

function Get-CroppedMaskData([bool[,]]$coreMask, [int]$width, [int]$height, [string]$digit) {
  $minX = $width
  $minY = $height
  $maxX = -1
  $maxY = -1

  for ($y = 0; $y -lt $height; $y++) {
    for ($x = 0; $x -lt $width; $x++) {
      if (-not $coreMask[$x, $y]) {
        continue
      }

      $minX = [Math]::Min($minX, $x)
      $minY = [Math]::Min($minY, $y)
      $maxX = [Math]::Max($maxX, $x)
      $maxY = [Math]::Max($maxY, $y)
    }
  }

  if ($maxX -lt 0 -or $maxY -lt 0) {
    throw "digit $digit has no yellow core pixels"
  }

  $pad = 2
  $cropX0 = [Math]::Max(0, $minX - $pad)
  $cropY0 = [Math]::Max(0, $minY - $pad)
  $cropX1 = [Math]::Min($width - 1, $maxX + $pad)
  $cropY1 = [Math]::Min($height - 1, $maxY + $pad)
  $cropW = $cropX1 - $cropX0 + 1
  $cropH = $cropY1 - $cropY0 + 1
  $cropped = New-Object 'bool[,]' $cropW, $cropH

  for ($y = 0; $y -lt $cropH; $y++) {
    for ($x = 0; $x -lt $cropW; $x++) {
      $cropped[$x, $y] = $coreMask[($cropX0 + $x), ($cropY0 + $y)]
    }
  }

  return @{
    mask = $cropped
    w = $cropW
    h = $cropH
    sourceX = $cropX0
    sourceY = $cropY0
  }
}

$digits = [ordered]@{}

foreach ($digit in $digitOrder) {
  $filePath = Join-Path $sourceDir ($digit + ".png")
  if (-not (Test-Path -LiteralPath $filePath)) {
    throw "missing digit source: $filePath"
  }

  $bitmap = [System.Drawing.Bitmap]::FromFile($filePath)
  try {
    $width = $bitmap.Width
    $height = $bitmap.Height
    $coreMask = New-Object 'bool[,]' $width, $height

    for ($y = 0; $y -lt $height; $y++) {
      for ($x = 0; $x -lt $width; $x++) {
        $color = $bitmap.GetPixel($x, $y)
        if (Test-IsYellowCorePixel $color) {
          $coreMask[$x, $y] = $true
        }
      }
    }

    $croppedData = Get-CroppedMaskData $coreMask $width $height $digit
    $croppedCore = $croppedData.mask
    $cropW = $croppedData.w
    $cropH = $croppedData.h
    $lightMask = Get-ExpandedMask $croppedCore $cropW $cropH
    $darkMask = Get-ExpandedMask $lightMask $cropW $cropH
    $rows = New-Object System.Collections.Generic.List[string]

    for ($y = 0; $y -lt $cropH; $y++) {
      $builder = New-Object System.Text.StringBuilder
      for ($x = 0; $x -lt $cropW; $x++) {
        if ($croppedCore[$x, $y]) {
          [void]$builder.Append("Y")
        } elseif ($lightMask[$x, $y]) {
          [void]$builder.Append("L")
        } elseif ($darkMask[$x, $y]) {
          [void]$builder.Append("D")
        } else {
          [void]$builder.Append(".")
        }
      }
      $rows.Add($builder.ToString())
    }

    $digits[$digit] = [ordered]@{
      w = $cropW
      h = $cropH
      sourceX = $croppedData.sourceX
      sourceY = $croppedData.sourceY
      rows = @($rows)
    }
  } finally {
    $bitmap.Dispose()
  }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated by assets-raw/spongebob/build-timefont-pixels.ps1")
$lines.Add("// Three-layer cleaned font: yellow core + light blue ring + dark blue outer ring")
$lines.Add("const SPONGEBOB_TIMEFONT = {")
$lines.Add("  order: ['0','1','2','3','4','5','6','7','8','9'],")
$lines.Add("  transparent: '.',")
$lines.Add("  symbols: 'YLD',")
$lines.Add("  paletteMap: {")
$lines.Add("    Y: '$yellow',")
$lines.Add("    L: '$lightBlue',")
$lines.Add("    D: '$darkBlue'")
$lines.Add("  },")
$lines.Add("  digits: {")

for ($digitIndex = 0; $digitIndex -lt $digitOrder.Count; $digitIndex++) {
  $digit = $digitOrder[$digitIndex]
  $digitData = $digits[$digit]
  $digitComma = if ($digitIndex -lt $digitOrder.Count - 1) { "," } else { "" }

  $lines.Add("    '$digit': {")
  $lines.Add("      w: $($digitData.w),")
  $lines.Add("      h: $($digitData.h),")
  $lines.Add("      sourceX: $($digitData.sourceX),")
  $lines.Add("      sourceY: $($digitData.sourceY),")
  $lines.Add("      rows: [")

  for ($rowIndex = 0; $rowIndex -lt $digitData.rows.Count; $rowIndex++) {
    $rowComma = if ($rowIndex -lt $digitData.rows.Count - 1) { "," } else { "" }
    $rowText = $digitData.rows[$rowIndex].Replace("\", "\\").Replace("'", "\'")
    $lines.Add("        '$rowText'$rowComma")
  }

  $lines.Add("      ]")
  $lines.Add("    }$digitComma")
}

$lines.Add("  }")
$lines.Add("};")
$lines.Add("")
$lines.Add("if (typeof window !== 'undefined') {")
$lines.Add("  window.SPONGEBOB_TIMEFONT = SPONGEBOB_TIMEFONT;")
$lines.Add("}")
$lines.Add("")
$lines.Add("if (typeof module !== 'undefined' && module.exports) {")
$lines.Add("  module.exports = SPONGEBOB_TIMEFONT;")
$lines.Add("}")
$lines.Add("")

[System.IO.File]::WriteAllLines($outputPath, $lines)

Write-Output ("generated: {0}" -f $outputPath)
Write-Output "palette: Y/L/D"
